"use client";
import {useState} from "react";
import s from "./renewal.module.css";
export default function ContactForm(){
 const [status,setStatus]=useState("");
 const [topic,setTopic]=useState("");
 function prepare(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const fields=[['お名前','name'],['会社名・団体名','organization'],['メールアドレス','email'],['電話番号','phone'],['相談内容','topic'],['希望する連携内容','collaboration'],['メッセージ','message']];const body=fields.map(([label,key])=>`${label}：${data.get(key)||'未記入'}`).join('\n\n');window.location.href=`mailto:info@musubu.or.jp?subject=${encodeURIComponent(`【結へのご相談】${data.get('topic')}`)}&body=${encodeURIComponent(body)}`;setStatus('内容を確認し、メールアプリから送信してください。このページでは送信は完了していません。メールアプリが開かない場合は、上記アドレスへ直接ご連絡ください。');}
 return <form onSubmit={prepare} className={s.form}><p className={s.formIntro}>ご相談内容を入力してください。<br/><small>入力後にメールアプリが開きます。自動送信はされません。</small></p><fieldset className={s.consultChoices}><legend>どんなことを、一緒に考えましょう。</legend>{[["健康講座","講座をお願いしたい"],["地域イベント","イベントで協力したい"],["食生活相談・予防支援","食生活を相談したい"]].map(([value,label])=><button key={value} type="button" aria-pressed={topic===value} onClick={()=>setTopic(value)}>{label}<span aria-hidden="true">↗</span></button>)}</fieldset><div className={s.formGrid}><label htmlFor="contact-name">お名前 <small>必須</small><input id="contact-name" name="name" autoComplete="name" required maxLength={100}/></label><label htmlFor="contact-org">会社名・団体名<input id="contact-org" name="organization" autoComplete="organization" maxLength={150}/></label><label htmlFor="contact-email">メールアドレス <small>必須</small><input id="contact-email" name="email" type="email" autoComplete="email" required maxLength={254}/></label><label htmlFor="contact-phone">電話番号<input id="contact-phone" name="phone" type="tel" autoComplete="tel" maxLength={40}/></label></div><label htmlFor="contact-topic">相談内容 <small>必須</small><select id="contact-topic" name="topic" required value={topic} onChange={e=>setTopic(e.target.value)}><option value="" disabled>選択してください</option><option>健康講座</option><option>食生活相談・予防支援</option><option>地域イベント</option><option>美容・休養プログラム</option><option>企業・店舗とのコラボ企画</option><option>コミュニティづくり</option><option>その他のご相談</option></select></label><label htmlFor="contact-collab">希望する連携内容<input id="contact-collab" name="collaboration" maxLength={200} placeholder="例：地域のマルシェで食育体験を行いたい"/></label><label htmlFor="contact-message">メッセージ <small>必須</small><textarea id="contact-message" name="message" rows={5} maxLength={1500} required placeholder="目的や時期など、決まっている範囲でお聞かせください。"/></label><p className={s.formNote}>入力内容はこのページには保存されません。ご利用のメールアプリで、宛先と本文をご確認のうえ送信してください。</p><button className={s.button} type="submit">内容をメールで相談する <span aria-hidden="true">↗</span></button><p role="status" aria-live="polite" className={s.status}>{status}</p></form>;
}



