import Image from "next/image";
import ContactForm from "./contact-form";
import MobileMenu from "./mobile-menu";
import MotionExperience from "./motion";
import s from "./renewal.module.css";


const nav = [["about", "結の想い"], ["elements", "食・動・美・心"], ["activities", "できること"], ["message", "代表メッセージ"]];
const elements = [
  {name:"食", en:"FOOD", color:"#E8C766", image:"element-food.jpg", alt:"ごはんと野菜のある食卓のイメージ", title:"食から、暮らしへ。", body:"毎日の食事を、無理なく見直すことから。栄養の知識を、その人の生活に合う選び方や食べ方へつなげます。", tags:"栄養講座 / 食生活相談 / 健康レシピ / 食育"},
  {name:"動", en:"MOVEMENT", color:"#D9877B", image:"element-movement-v4.png", alt:"自然光の中で身体を動かすイメージ", title:"動きから、めぐりへ。", body:"少し歩く、ゆっくり伸ばす。特別な運動だけでなく、暮らしの中で身体を動かすきっかけを一緒に見つけます。", tags:"運動習慣 / 健康イベント / 姿勢 / 体験型プログラム"},
  {name:"美", en:"BEAUTY", color:"#9DBE9A", image:"element-beauty-v4.png", alt:"朝の光の中、手にクリームをなじませるセルフケアのイメージ", title:"美しさから、自信へ。", body:"肌や姿勢をいたわり、自分に目を向ける時間を。誰かの基準ではなく、その人らしく心地よく過ごすためのケアを考えます。", tags:"美容と健康 / セルフケア / 休養 / 自分らしさ"},
  {name:"心", en:"MIND", color:"#8FAFC7", image:"element-mind-v4.png", alt:"お茶とともに心を休めるイメージ", title:"休むことから、明日へ。", body:"休むことも、毎日の大切な習慣。睡眠や休養を見直すこと、安心して話せる場を持つことから、心に余白をつくります。", tags:"休養 / 睡眠 / 対話の場 / コミュニティ"}
];
const services = [
  ["健康講座", "管理栄養士の視点から、食事、栄養、予防、生活習慣をわかりやすく。企業研修、地域講座、学校・施設など、目的に合わせた学びを企画します。"],
  ["食生活相談・予防支援", "毎日の食事や生活習慣を見直し、その人の暮らしに合った、無理なく続けられる形を一緒に考えます。"],
  ["地域イベント", "マルシェ、交流会、体験会。食べる、話す、体験する場に、自然に健康を意識できるきっかけをつくります。"],
  ["美容・休養プログラム", "美容、セルフケア、睡眠、休養。自分らしく前向きに過ごすための整え方を、幅広い視点から届けます。"],
  ["企業・店舗とのコラボ企画", "健康メニュー、商品監修、セミナー、情報発信。企業や店舗、専門家とともに、想いが一度きりで終わらない形を考えます。"],
  ["コミュニティづくり", "人と人がつながり、学び合い、支え合える場を。暮らしの中に、健やかさを続けるための小さな輪を広げます。"]
];
function Label({children}:{children:React.ReactNode}) {return <p className={s.label}>{children}</p>;}
function Photo({src,alt,className="",priority=false}:{src:string;alt:string;className?:string;priority?:boolean}) {return <div data-parallax={!priority ? "true" : undefined} data-reveal={!priority ? "photo" : undefined} className={`${s.photo} ${className}`}><Image src={`/images/${src}`} alt={alt} fill sizes={priority ? "100vw" : "(max-width: 700px) 100vw, 55vw"} priority={priority}/></div>;}
function Mark({className=""}:{className?:string}) {return <Image className={className} src="/images/renewal-musubu-mark.png" width={190} height={105} alt=""/>;}

export default function RenewalContent({opening,header,className=""}:{opening?:React.ReactNode;header?:React.ReactNode;className?:string}={}){return <div className={`${s.page} ${className}`} id="top"><MotionExperience/>
  <a className={s.skip} href="#main">本文へ移動</a>
  {header ?? <header className={s.header}>
    <a href="#top" aria-label="一般社団法人 結 トップへ" className={s.logo}><Mark/><span>MUSUBU<small>一般社団法人 結</small></span></a>
    <nav className={s.nav} aria-label="メインナビゲーション">{nav.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
    <a className={s.headerContact} href="#contact">ご相談・お問い合わせ <span aria-hidden="true">↗</span></a>
    <MobileMenu/>
  </header>}
  <main id="main">
    {opening ?? <>
    <section data-hero className={s.hero} aria-labelledby="hero-title">
      <div className={s.heroVisual}><Photo src="rice-hero-v2.png" alt="白米の一粒一粒にやわらかな光が透ける" priority/></div>
      <div className={s.heroCopy}><Label>MUSUBU / WELLBEING IN EVERYDAY LIFE</Label><h1 id="hero-title">暮らしを整え、<br/>人と人を結ぶ。</h1><p className={s.heroLead}>食・動・美・心。<br/>健やかさは、日々のつながりから。</p></div>
      <div className={s.heroAside}><p>ひとりでは続かないことも、<br/>誰かとなら、少しずつ。</p><a className={s.button} href="#about">結について知る <span aria-hidden="true">↗</span></a></div>
      <a className={s.heroScroll} href="#about">SCROLL <span aria-hidden="true">↓</span></a>
    </section>
    <div className={s.heroFoot}><span>一般社団法人 結</span><span>食べる。動く。整える。休む。</span><a href="#contact">活動について相談する ↗</a></div>
    <section data-bridge className={s.bridge} aria-label="一粒から、暮らしへ"><div className={s.bridgeSticky}><div className={s.bridgePhoto}><Image src="/images/rice-serving-morning.png" loading="eager" alt="湯気の立つごはんをよそう手元のイメージ" fill sizes="(max-width: 760px) 1500px, 100vw"/></div><div className={s.bridgeWords}><p>FROM A GRAIN TO A CONNECTION</p><h2><span>一粒から、暮らしへ。</span><span>その食卓から、つながりへ。</span></h2></div><svg className={s.connectingLines} viewBox="0 0 1000 180" fill="none" aria-hidden="true">{['#c9b66a','#c79286','#95ac91','#8aa5b4'].map((color,i)=><path key={color} pathLength="1" stroke={color} strokeWidth="1.5" d={`M -30 ${30+i*9} C 250 ${30+i*9}, 260 ${150-i*9}, 510 ${150-i*9} S 800 ${25+i*8}, 1030 ${75+i*10}`}/>)}</svg></div></section>
    <section id="about" className={s.intro}><Label>Our philosophy</Label><h2 data-reveal="text">人と人を結ぶ、<br/>健康づくりの輪。</h2><p>食・動・美・心の調和から、<br/>毎日の暮らしをやさしく整える。</p><p>ひとりでは続かないことも、<br/>誰かとなら、少しずつ。</p><div className={s.fourDots} aria-hidden="true"><i/><i/><i/><i/></div></section>
    <section className={s.together} aria-labelledby="together-title"><figure className={s.sharedFigure} data-reveal="photo"><div className={s.sharedPhoto}><Image src="/images/shared-dining-edited.png" alt="自然光の中で食卓を囲む3人のイメージ（提供写真をAI加工）" fill sizes="(max-width: 760px) 1000px, 100vw"/></div><figcaption>食卓を囲むイメージ / 提供写真をAI加工</figcaption></figure><div className={s.togetherCopy}><div><Label>Everyday connections</Label><h2 id="together-title" data-reveal="text">誰かと囲む食卓に、<br/>健やかな明日の種がある。</h2></div><div><p>食べること。話すこと。<br/>一緒に、笑うこと。</p><p>そんな何気ない時間も、<br/>暮らしを整える大切なひとつ。</p><p>結は、学びや体験、人とのつながりを通して、<br/>その人らしい健康づくりに寄り添います。</p><a className={s.editorialLink} href="#elements">食・動・美・心を知る <span aria-hidden="true">↗</span></a></div></div></section>
    </>}
    <section data-layout="circle" className={s.circleSection} aria-labelledby="circle-title"><div className={s.circleText}><Label>MUSUBU WELLNESS CIRCLE</Label><h2 data-reveal="text" id="circle-title">小さなつながりが、<br/>暮らしを支える。</h2><p>学ぶ。体験する。話す。気づく。<br/>そして、また続けてみる。</p><p>目指すのは、暮らしに小さな変化が残る健康づくり。<br/>管理栄養士の専門性を軸に、地域、企業、店舗、<br className={s.desktopBreak}/>専門家、参加する人たちを結びます。</p><p>自分の健やかさが、家族へ、地域へ。<br/>その輪を、一緒に育てていきます。</p></div><div data-circle className={s.circle} aria-label="食・動・美・心を中心に、人、地域、企業、専門家がつながる輪"><Mark/>{["食","地域","動","企業","美","専門家","心","人"].map((label,i)=><span key={label} className={s[`orbit${i}`]}>{label}</span>)}</div></section>
    <section data-layout="elements" id="elements" className={s.section}><div className={s.sectionHeading}><div><Label>FOUR ELEMENTS</Label><h2 data-reveal="text">食べる。動く。<br/>整える。休む。</h2></div><p>ロゴの「あわじ結び」のように、4つの視点を結びながら。その人の暮らしに合う整え方を探します。</p></div><div data-journey className={s.journey}><div className={s.journeyStage} aria-hidden="true">{elements.map((e,i)=><div key={e.name} data-stage data-active={i===0 ? "true" : "false"} className={s.stageImage}><Image src={`/images/${e.image}`} alt="" fill sizes="55vw"/></div>)}<svg data-theme-threads viewBox="0 0 600 180" fill="none" aria-hidden="true">{["#d0b576","#bc897e","#8caa82","#8faebe"].map((color,i)=><path key={color} data-theme-thread={i} data-active={i===0?"true":"false"} pathLength="1" stroke={color} strokeWidth="2" strokeLinecap="round" d={`M -20 ${140+i*5} C 90 ${150+i*5}, 145 ${32+i*5}, 265 ${35+i*5} C 385 ${38+i*5}, 330 ${154-i*5}, 252 ${130-i*5} C 175 ${104-i*5}, 295 ${45+i*5}, 375 ${70+i*5} S 530 ${160-i*5}, 620 ${50+i*5}`}/>)}</svg><div className={s.journeyCaption}><span>FOUR ELEMENTS</span><span><b data-count>01</b> / 04</span></div></div><div className={s.elements}>{elements.map(e=><article data-story key={e.name} className={s.element} style={{"--element-color":e.color} as React.CSSProperties}><Photo src={e.image} alt={e.alt}/><span data-local-thread aria-hidden="true"/><div className={s.elementName}><span>{e.name}</span><small>{e.en}</small></div><h3>{e.title}</h3><p>{e.body}</p><p className={s.tags}>{e.tags}</p></article>)}</div></div></section>
    <section data-layout="activities" id="activities" className={`${s.section} ${s.activities}`}><div className={s.sectionHeading}><div><Label>WHAT WE DO</Label><h2 data-reveal="text">学び、体験し、<br/>人がつながる。</h2></div><p>知ることから、やってみることへ。講座、個別の相談、地域のイベントなど、目的や参加する方に合わせて企画します。</p></div><div className={s.services}>{services.map(([title,body],i)=><article data-reveal="text" key={title}><span className={s.number}>0{i+1}</span><h3>{title}</h3><p>{body}</p><a href={`#contact`} className={s.serviceLink} aria-label={`${title}について相談する`}>この活動について相談する <span aria-hidden="true">↗</span></a></article>)}</div></section>
    <section data-layout="director" id="message" className={`${s.section} ${s.director}`}><div><Photo src="director-watanabe.jpg" alt="一般社団法人 結 理事長 渡邉裕子" className={s.directorPhoto}/><p className={s.directorCaption}>一般社団法人 結 理事長 / 管理栄養士<strong>渡邉 裕子</strong></p></div><div><Label>MESSAGE</Label><h2 data-reveal="text">暮らしに寄り添い、<br/>健康づくりの輪を結ぶ。</h2><p>管理栄養士として、病院での給食管理・衛生管理・臨床栄養業務・栄養指導に携わり、その後、調剤薬局での健康相談や健康セミナーを経験してきました。</p><p>現場で多くの方と関わる中で感じたのは、健康は知識だけでは続かないということです。</p><p>忙しさや不安、生活環境によって、わかっていても続けられない日があります。だからこそ、正しさを伝えるだけでなく、その人の暮らしに合う方法を一緒に考えたいと思っています。</p><p>ひとりで抱え込まず、相談できる人や場所があること。結を、そんな小さな一歩を支える場に育てていきます。</p><details className={s.biography}><summary>これまでの歩み</summary><dl><dt>2015</dt><dd>仙台白百合女子大学 人間学部 健康栄養学科卒業。病院・調剤薬局で栄養指導、健康相談、健康セミナーに従事。</dd><dt>2020</dt><dd>名古屋へ移住。フリーランス管理栄養士として特定保健指導に携わり、健康分野の情報発信・ブランディング支援にも取り組む。</dd><dt>2024</dt><dd>7月、一般社団法人 結を設立。食・動・美・心をテーマに、地域の健康づくりと人がつながる場づくりに取り組む。</dd></dl></details></div></section>
    <section data-layout="partnership" id="partnership" className={s.partnership}><div className={s.sectionHeading}><div><Label>CREATE TOGETHER</Label><h2 data-reveal="text">食・動・美・心 × 地域で、<br/>新しい健康づくりを。</h2></div><p>地域イベントに食育を取り入れる。職場で食生活を学ぶ。店舗や商品に健康の視点を加える。目的と対象を伺い、企画から実施・発信までの形を一緒に考えます。</p></div><div className={s.partners}>{["地域イベント","企業研修","美容サロン","飲食店","医療・福祉","学校","マルシェ","商品監修","情報発信","コミュニティづくり"].map(t=><a key={t} href="#contact"><span>結 ×</span> {t}</a>)}</div><div className={s.steps}>{[["相談する","想いや課題を伺う"],["一緒に考える","目的・対象・実現方法を整理する"],["人を結ぶ","地域や専門家と企画をつくる"],["次につなぐ","実施と発信、その先へ"]].map(([t,b],i)=><div key={t}><small>0{i+1}</small><h3>{t}</h3><p>{b}</p></div>)}</div></section>
    <section data-layout="journal" id="reports" className={`${s.section} ${s.reports}`}><div><Label>JOURNAL</Label><h2 data-reveal="text">日々の活動を、<br/>お届けします。</h2><p>講座やイベントの様子、結からのお知らせを、公式InstagramとXで発信しています。</p></div><div className={s.reportEmpty}><span>活動レポート・お知らせ</span><h3>日々の結びを、もっと身近に。</h3><p>最新の投稿は、こちらからご覧いただけます。</p><a className={s.textLink} href="https://www.instagram.com/musubu_kenkou/" target="_blank" rel="noopener noreferrer">Instagramで活動を見る <span aria-hidden="true">↗</span></a><a className={s.textLink} href="https://x.com/musubu_kenkou" target="_blank" rel="noopener noreferrer">公式Xでお知らせを見る <span aria-hidden="true">↗</span></a><p className={s.instagramHandle}>Instagram / X — @musubu_kenkou</p></div></section>
    <section data-layout="contact" id="contact" className={s.contact}><div className={s.contactIntro}><Label>CONTACT</Label><h2 data-reveal="text">小さな相談から、<br/>一緒に結んでいく。</h2><p>「こんなことはできる？」という段階でも大丈夫です。目的や時期、参加する方など、決まっている範囲でお聞かせください。</p><a href="mailto:info@musubu.or.jp" className={s.email}>info@musubu.or.jp</a><p className={s.contactNote}>メールでのお問い合わせも受け付けています。</p></div><ContactForm/></section>
    <section data-layout="organization" id="organization" className={`${s.section} ${s.organization}`}><div><Label>ORGANIZATION</Label><h2 data-reveal="text">結について</h2></div><dl>{[["法人名","一般社団法人 結（むすぶ）"],["英字表記","MUSUBU"],["設立","2024年7月29日"],["理事長","渡邉 裕子"],["主なテーマ","食・動・美・心"],["主な活動","健康講座、食生活相談、地域イベント、企業・店舗との連携、美容・休養に関する企画、コミュニティづくり"]].map(([t,d])=><div key={t}><dt>{t}</dt><dd>{d}</dd></div>)}</dl></section>
  </main><footer data-layout="footer" className={s.footer}><div><Mark/><p>食べること。動くこと。<br/>整えること。休むこと。</p><p>人とのつながりの中で、<br/>健やかな毎日を結んでいく。</p></div><div className={s.footerLinks}><a href="#about">結の想い</a><a href="#activities">結ができること</a><a href="#reports">活動レポート</a><a href="#organization">法人概要</a><a href="#contact">お問い合わせ</a><a href="https://www.instagram.com/musubu_kenkou/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://x.com/musubu_kenkou" target="_blank" rel="noopener noreferrer">公式X ↗</a></div><div className={s.footerWord} aria-hidden="true">MUSUBU</div><div className={s.footerBottom}><span>一般社団法人 結 / MUSUBU</span><small>© MUSUBU</small><a href="#top">ページの先頭へ ↑</a></div></footer>
</div>;}



